import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import {ClerkProvider} from "@clerk/nextjs";
import './globals.css';
import { Toaster } from "sonner";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400", "700"], // Adjust weights as needed
  subsets: ["latin"],
  display: "swap",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Realtyx",
  description: "Generated by Fenil Sheta",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.className} antialiased`}
        >
          <Provider>
          <Toaster />
            {children}
            
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
